import { MentorUser, MenteeUser, MentorSummaryStats } from "@/types/user";

export const mockMentorStats: MentorSummaryStats = {
  totalMentors: 148,
  activeCount: 132,
  inactiveCount: 16,
  quarterTrend: "+8 this quarter",
  partnerFacilities: 12,
  teachingHospitals: 9,
  clinicsCount: 3,
  activeMentees: 412,
  avgPerPreceptor: 2.8,
  loadStatus: "Optimal Load",
  completionPercentage: 94.6,
  completionTrend: "↑1.4%",
  completionTarget: 92,
};

export const mockMentors: MentorUser[] = [
  {
    id: "m-1",
    systemId: "MEN-2024-001",
    name: "Sister Almaz Bekele, MSc",
    email: "almaz.bekele@sphmmc.edu.et",
    phone: "+251 91 123 4567",
    role: "mentor",
    avatarInitials: "AB",
    avatarBgColor: "bg-blue-100 text-blue-700",
    profession: "Lead Midwifery Preceptor",
    department: "Maternal & Fetal Health Unit",
    facility: "St. Paul's Hospital Millennium Medical College (SPHMMC)",
    facilityType: "Teaching Hospital",
    thematicArea: "Maternal & Child",
    yearsOfExperience: 14,
    assignedMenteesCount: 5,
    status: "active",
  },
  {
    id: "m-2",
    systemId: "MEN-2024-014",
    name: "Dr. Dawit Hailemariam, MD",
    email: "dawit.hailemariam@tash.edu.et",
    phone: "+251 91 234 5678",
    role: "mentor",
    avatarInitials: "DH",
    avatarBgColor: "bg-amber-100 text-amber-700",
    profession: "Senior Obstetrician-Gynecologist",
    department: "High-Risk Labor & Delivery Ward",
    facility: "Tikur Anbessa Specialized Hospital (TASH)",
    facilityType: "Teaching Hospital",
    thematicArea: "Emergency Care",
    yearsOfExperience: 11,
    assignedMenteesCount: 4,
    status: "active",
  },
  {
    id: "m-3",
    systemId: "MEN-2024-028",
    name: "Sister Bethlehem Tadesse, MSc",
    email: "bethlehem.tadesse@hu.edu.et",
    phone: "+251 91 345 6789",
    role: "mentor",
    avatarInitials: "BT",
    avatarBgColor: "bg-rose-100 text-rose-700",
    profession: "Neonatal Midwife Specialist",
    department: "Neonatal Intensive Care Unit (NICU)",
    facility: "Hawassa University Comprehensive Hospital",
    facilityType: "Teaching Hospital",
    thematicArea: "Pediatrics & Neo",
    yearsOfExperience: 9,
    assignedMenteesCount: 6,
    status: "active",
  },
  {
    id: "m-4",
    systemId: "MEN-2024-035",
    name: "Dr. Yohannes Kebede, MD, MPH",
    email: "yohannes.kebede@uog.edu.et",
    phone: "+251 91 456 7890",
    role: "mentor",
    avatarInitials: "YK",
    avatarBgColor: "bg-purple-100 text-purple-700",
    profession: "Consultant Obstetric Surgeon",
    department: "Maternity Surgical Theatre",
    facility: "University of Gondar Comprehensive Hospital",
    facilityType: "Teaching Hospital",
    thematicArea: "Surgery & Critical",
    yearsOfExperience: 16,
    assignedMenteesCount: 3,
    status: "active",
  },
  {
    id: "m-5",
    systemId: "MEN-2024-052",
    name: "Sister Selamawit Desta, BSc",
    email: "selamawit.desta@ju.edu.et",
    phone: "+251 91 567 8901",
    role: "mentor",
    avatarInitials: "SD",
    avatarBgColor: "bg-indigo-100 text-indigo-700",
    profession: "Senior Adolescent Health Preceptor",
    department: "Youth-Friendly SRH Clinic",
    facility: "Jimma University Medical Center (JUMC)",
    facilityType: "Teaching Hospital",
    thematicArea: "Internal Medicine",
    yearsOfExperience: 10,
    assignedMenteesCount: 4,
    status: "active",
  },
  {
    id: "m-6",
    systemId: "MEN-2024-077",
    name: "Dr. Tadesse Worku, MD",
    email: "tadesse.worku@fhcsh.gov.et",
    phone: "+251 91 678 9012",
    role: "mentor",
    avatarInitials: "TW",
    avatarBgColor: "bg-teal-100 text-teal-700",
    profession: "PMTCT & Infectious Disease Specialist",
    department: "Maternal Infectious Disease Unit",
    facility: "Felege Hiwot Comprehensive Specialized Hospital",
    facilityType: "Regional Center",
    thematicArea: "Infectious Diseases",
    yearsOfExperience: 13,
    assignedMenteesCount: 2,
    status: "inactive",
  },
  {
    id: "m-7",
    systemId: "MEN-2024-093",
    name: "Sister Gennet Assefa, MSc",
    email: "gennet.assefa@yekatit12.gov.et",
    phone: "+251 91 789 0123",
    role: "mentor",
    avatarInitials: "GA",
    avatarBgColor: "bg-orange-100 text-orange-700",
    profession: "EmONC Clinical Trainer",
    department: "Emergency Obstetric Resuscitation",
    facility: "Yekatit 12 Hospital Medical College",
    facilityType: "Teaching Hospital",
    thematicArea: "Emergency Care",
    yearsOfExperience: 8,
    assignedMenteesCount: 3,
    status: "active",
  },
];

export const mockMentees: MenteeUser[] = [
  {
    id: "mnt-1",
    systemId: "MNT-2024-089",
    name: "Marta Getachew",
    email: "marta.getachew@sphmmc.edu.et",
    phone: "+251 92 111 2233",
    role: "mentee",
    avatarInitials: "MG",
    avatarBgColor: "bg-emerald-100 text-emerald-700",
    profession: "Midwife Intern",
    cadreLevel: "Year 2 Clinical Practicum",
    facility: "St. Paul's Hospital Millennium Medical College (SPHMMC)",
    thematicArea: "Maternal & Child",
    assignedMentor: {
      name: "Sister Almaz Bekele, MSc",
      title: "Lead Midwifery Preceptor",
      avatarInitials: "AB",
      status: "assigned",
    },
    knowledgeScore: 94,
    scoreTier: "Tier 1",
    status: "active",
  },
  {
    id: "mnt-2",
    systemId: "MNT-2024-094",
    name: "Kassahun Mengistu",
    email: "kassahun.mengistu@tash.edu.et",
    phone: "+251 92 222 3344",
    role: "mentee",
    avatarInitials: "KM",
    avatarBgColor: "bg-amber-100 text-amber-700",
    profession: "Junior Clinical Midwife",
    cadreLevel: "Labor & Delivery Ward Rotation",
    facility: "Tikur Anbessa Specialized Hospital (TASH)",
    thematicArea: "Emergency Care",
    assignedMentor: {
      name: "Dr. Dawit Hailemariam, MD",
      title: "Senior Obstetrician-Gynecologist",
      avatarInitials: "DH",
      status: "assigned",
    },
    knowledgeScore: 76,
    scoreTier: "Tier 2",
    status: "active",
  },
  {
    id: "mnt-3",
    systemId: "MNT-2024-102",
    name: "Hiwot Alemayehu",
    email: "hiwot.alemayehu@hu.edu.et",
    phone: "+251 92 333 4455",
    role: "mentee",
    avatarInitials: "HA",
    avatarBgColor: "bg-blue-100 text-blue-700",
    profession: "Resident Midwife",
    cadreLevel: "Neonatal Clinical Trainee",
    facility: "Hawassa University Comprehensive Hospital",
    thematicArea: "Pediatrics & Neo",
    assignedMentor: {
      name: "Sister Bethlehem Tadesse, MSc",
      title: "Neonatal Midwife Specialist",
      avatarInitials: "BT",
      status: "assigned",
    },
    knowledgeScore: 89,
    scoreTier: "Tier 1",
    status: "active",
  },
  {
    id: "mnt-4",
    systemId: "MNT-2024-118",
    name: "Ephrem Tesfaye",
    email: "ephrem.tesfaye@uog.edu.et",
    phone: "+251 92 444 5566",
    role: "mentee",
    avatarInitials: "ET",
    avatarBgColor: "bg-purple-100 text-purple-700",
    profession: "Midwife Student",
    cadreLevel: "Undergraduate Intern",
    facility: "University of Gondar Comprehensive Hospital",
    thematicArea: "Surgery & Critical",
    assignedMentor: {
      name: "Dr. Yohannes Kebede, MD, MPH",
      title: "Consultant Obstetric Surgeon",
      avatarInitials: "YK",
      status: "assigned",
    },
    knowledgeScore: 68,
    scoreTier: "Tier 2",
    status: "pending_start",
  },
  {
    id: "mnt-5",
    systemId: "MNT-2024-121",
    name: "Tigist Abebe",
    email: "tigist.abebe@ju.edu.et",
    phone: "+251 92 555 6677",
    role: "mentee",
    avatarInitials: "TA",
    avatarBgColor: "bg-rose-100 text-rose-700",
    profession: "Clinical Midwife Officer",
    cadreLevel: "Adolescent SRHR Fellow",
    facility: "Jimma University Medical Center (JUMC)",
    thematicArea: "Internal Medicine",
    assignedMentor: {
      name: "Sister Selamawit Desta, BSc",
      title: "Senior Adolescent Health Preceptor",
      avatarInitials: "SD",
      status: "assigned",
    },
    knowledgeScore: 82,
    scoreTier: "Tier 1",
    status: "active",
  },
  {
    id: "mnt-6",
    systemId: "MNT-2024-129",
    name: "Chaltu Tolosa",
    email: "chaltu.tolosa@fhcsh.gov.et",
    phone: "+251 92 666 7788",
    role: "mentee",
    avatarInitials: "CT",
    avatarBgColor: "bg-teal-100 text-teal-700",
    profession: "Midwife Practitioner",
    cadreLevel: "PMTCT Post-Graduate Fellow",
    facility: "Felege Hiwot Comprehensive Specialized Hospital",
    thematicArea: "Infectious Diseases",
    assignedMentor: {
      name: "Dr. Tadesse Worku, MD",
      title: "PMTCT & Infectious Disease Specialist",
      avatarInitials: "TW",
      status: "assigned",
    },
    knowledgeScore: 59,
    scoreTier: "Remediation",
    status: "inactive",
  },
  {
    id: "mnt-7",
    systemId: "MNT-2024-142",
    name: "Birtukan Kassa",
    email: "birtukan.kassa@yekatit12.gov.et",
    phone: "+251 92 777 8899",
    role: "mentee",
    avatarInitials: "BK",
    avatarBgColor: "bg-orange-100 text-orange-700",
    profession: "Midwife Intern",
    cadreLevel: "Clinical Skills Practicum",
    facility: "Yekatit 12 Hospital Medical College",
    thematicArea: "Emergency Care",
    assignedMentor: {
      status: "unassigned",
    },
    knowledgeScore: 71,
    scoreTier: "Tier 2",
    status: "pending_start",
  },
];
