import { MentorUser, MenteeUser, MentorSummaryStats } from "@/types/user";

export const mockMentorStats: MentorSummaryStats = {
  totalMentors: 148,
  activeCount: 132,
  inactiveCount: 16,
  quarterTrend: "+8 this quarter",
  partnerFacilities: 12,
  teachingHospitals: 9,
  clinicsCount: 3,
  activeMentees: 412,
  avgPerPreceptor: 2.8,
  loadStatus: "Optimal Load",
  completionPercentage: 94.6,
  completionTrend: "↑1.4%",
  completionTarget: 92,
};

export const mockMentors: MentorUser[] = [
  {
    id: "m-1",
    systemId: "MEN-2024-001",
    name: "Dr. Elena Rostova",
    email: "elena.rostova@mercyhealth.org",
    phone: "+1 (555) 234-5678",
    role: "mentor",
    avatarInitials: "ER",
    avatarBgColor: "bg-blue-100 text-blue-700",
    profession: "Chief of Pediatrics",
    department: "Pediatric Intensive Care Unit",
    facility: "Mercy Children's Regional Center",
    facilityType: "Teaching Hospital",
    thematicArea: "Pediatrics & Neo",
    yearsOfExperience: 14,
    assignedMenteesCount: 5,
    status: "active",
  },
  {
    id: "m-2",
    systemId: "MEN-2024-014",
    name: "Dr. David K. Osei",
    email: "david.osei@northwesttrauma.org",
    phone: "+1 (555) 345-6789",
    role: "mentor",
    avatarInitials: "DO",
    avatarBgColor: "bg-amber-100 text-amber-700",
    profession: "Senior Emergency Physician",
    department: "Level 1 Trauma Service",
    facility: "Northwest Trauma & Specialty Hospital",
    facilityType: "Specialty Hospital",
    thematicArea: "Emergency Care",
    yearsOfExperience: 11,
    assignedMenteesCount: 4,
    status: "active",
  },
  {
    id: "m-3",
    systemId: "MEN-2024-028",
    name: "Sarah Al-Mansoor, MSN",
    email: "sarah.mansoor@stjude.org",
    phone: "+1 (555) 456-7890",
    role: "mentor",
    avatarInitials: "SA",
    avatarBgColor: "bg-rose-100 text-rose-700",
    profession: "Lead Clinical Nurse Preceptor",
    department: "Maternal & Fetal Health",
    facility: "St. Jude Teaching Hospital (Main)",
    facilityType: "Teaching Hospital",
    thematicArea: "Maternal & Child",
    yearsOfExperience: 9,
    assignedMenteesCount: 6,
    status: "active",
  },
  {
    id: "m-4",
    systemId: "MEN-2024-035",
    name: "Dr. Julian Sterling",
    email: "j.sterling@valleygeneral.org",
    phone: "+1 (555) 567-8901",
    role: "mentor",
    avatarInitials: "JS",
    avatarBgColor: "bg-purple-100 text-purple-700",
    profession: "Consultant General Surgeon",
    department: "Laparoscopic & Acute Care",
    facility: "Valley General Healthcare Center",
    facilityType: "Regional Center",
    thematicArea: "Surgery & Critical",
    yearsOfExperience: 16,
    assignedMenteesCount: 3,
    status: "active",
  },
  {
    id: "m-5",
    systemId: "MEN-2024-052",
    name: "Dr. Ananya Sharma",
    email: "a.sharma@apexcardiology.org",
    phone: "+1 (555) 678-9012",
    role: "mentor",
    avatarInitials: "AS",
    avatarBgColor: "bg-indigo-100 text-indigo-700",
    profession: "Attending Cardiologist",
    department: "Cardiovascular Clinical Fellow",
    facility: "Apex Cardiology Institute",
    facilityType: "Specialty Hospital",
    thematicArea: "Internal Medicine",
    yearsOfExperience: 10,
    assignedMenteesCount: 4,
    status: "active",
  },
  {
    id: "m-6",
    systemId: "MEN-2024-077",
    name: "Dr. Robert Chen",
    email: "robert.chen@citycentral.org",
    phone: "+1 (555) 789-0123",
    role: "mentor",
    avatarInitials: "RC",
    avatarBgColor: "bg-teal-100 text-teal-700",
    profession: "Infectious Disease Specialist",
    department: "Epidemiology & Outbreak Ops",
    facility: "City Central Community Clinic",
    facilityType: "Clinic",
    thematicArea: "Infectious Diseases",
    yearsOfExperience: 13,
    assignedMenteesCount: 2,
    status: "inactive",
  },
  {
    id: "m-7",
    systemId: "MEN-2024-093",
    name: "Michelle Thorne, PharmD",
    email: "m.thorne@highlandclinic.org",
    phone: "+1 (555) 890-1234",
    role: "mentor",
    avatarInitials: "MT",
    avatarBgColor: "bg-orange-100 text-orange-700",
    profession: "Clinical Pharmacotherapy Specialist",
    department: "Critical Resuscitation Care",
    facility: "Highland Memorial Clinic",
    facilityType: "Clinic",
    thematicArea: "Emergency Care",
    yearsOfExperience: 7,
    assignedMenteesCount: 3,
    status: "active",
  },
];

export const mockMentees: MenteeUser[] = [
  {
    id: "mnt-1",
    systemId: "MNT-2024-089",
    name: "Dr. Samantha Mills",
    email: "samantha.mills@cg-hospital.org",
    role: "mentee",
    avatarInitials: "SM",
    avatarBgColor: "bg-emerald-100 text-emerald-700",
    profession: "Resident Physician",
    cadreLevel: "PGY-2 Trauma Surgery",
    facility: "Central General - West Wing",
    thematicArea: "Emergency Care",
    assignedMentor: {
      name: "Dr. Miriam Kalu",
      title: "Lead Preceptor",
      avatarInitials: "MK",
      status: "assigned",
    },
    knowledgeScore: 94,
    scoreTier: "Tier 1",
    status: "active",
  },
  {
    id: "mnt-2",
    systemId: "MNT-2024-094",
    name: "Jonathan Davis",
    email: "j.davis@metropediatrics.org",
    role: "mentee",
    avatarInitials: "JD",
    avatarBgColor: "bg-amber-100 text-amber-700",
    profession: "Clinical Nurse Specialist",
    cadreLevel: "Pediatric Intensive Care",
    facility: "Metro Pediatric Hospital",
    thematicArea: "Pediatrics & Neo",
    assignedMentor: {
      name: "Dr. Aris Thorne",
      title: "Attending Intensivist",
      avatarInitials: "AT",
      status: "assigned",
    },
    knowledgeScore: 76,
    scoreTier: "Tier 2",
    status: "active",
  },
];

